# Generated by Django 4.1.3 on 2022-11-16 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=50, null=True)),
                ("dataNascimento", models.DateField()),
                ("nomeMae", models.CharField(blank=True, max_length=50)),
                ("prontuario", models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="SalaEsperaCC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pulseriaIdentificacao", models.CharField(max_length=1)),
                ("jejum", models.CharField(max_length=1)),
                ("inicioJ", models.TimeField()),
                ("triconomiaRealizada", models.CharField(max_length=1)),
                ("realizouBanho", models.CharField(max_length=1)),
                ("preparoIntestinal", models.CharField(max_length=1)),
                ("semProtese", models.CharField(max_length=1)),
                ("sitioCirurgico", models.CharField(max_length=1)),
                ("alergiasConhecidas", models.CharField(max_length=1)),
                ("qualAC", models.CharField(max_length=20)),
                ("riscoViaA", models.CharField(max_length=1)),
                ("equipamentoDisponivelRVA", models.IntegerField()),
                ("riscoPerdaSa", models.CharField(max_length=1)),
                ("equipamentosAnestesiaTF", models.CharField(max_length=15)),
                ("caixasInstrumentaisCPE", models.CharField(max_length=1)),
                ("formularioIdentificacao", models.CharField(max_length=1)),
                ("relatorioEnfermagem", models.CharField(max_length=1)),
                ("fichaSinaisV", models.CharField(max_length=1)),
                ("exameLaboratI", models.CharField(max_length=1)),
                ("consentimentoCirurgico", models.CharField(max_length=1)),
                ("consentimentoAnestesico", models.CharField(max_length=1)),
                ("avaliaçaoPreA", models.CharField(max_length=1)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="checklist.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cirurgia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cirurgiaProposta", models.CharField(max_length=50)),
                ("cirurgiaRealizada", models.CharField(max_length=50)),
                ("salaCirugica", models.CharField(max_length=50)),
                ("dataCirurugia", models.DateField()),
                ("modalidade", models.CharField(max_length=10)),
                ("realizouQuimeoterapia", models.CharField(max_length=1)),
                ("quantasSQ", models.IntegerField()),
                ("realizouRadioterapia", models.CharField(max_length=1)),
                ("quantasRR", models.IntegerField()),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="checklist.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AntesUsuarioSSC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrumentaisAntes", models.IntegerField()),
                ("compressasAntes", models.IntegerField()),
                ("agulhasAntes", models.IntegerField()),
                ("laminaBisturiAntes", models.IntegerField()),
                ("instrumentaisDepois", models.IntegerField()),
                ("compressasDepois", models.IntegerField()),
                ("agulhasDepois", models.IntegerField()),
                ("laminaBisturiDepois", models.IntegerField()),
                ("RegistoCompletoPIRLP", models.CharField(max_length=1)),
                ("houveAglumPMEI", models.CharField(max_length=1)),
                ("QualHAPMEI", models.CharField(max_length=1)),
                ("altaConfirmadaAE", models.CharField(max_length=1)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="checklist.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AntesInicisaoC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("todosProfissionaisCNF", models.CharField(max_length=1)),
                ("cirurgiaoAnestesistaEEC", models.CharField(max_length=15)),
                ("antibioticoProfilaticoAU", models.CharField(max_length=1)),
                ("horaAPAU", models.TimeField()),
                ("examesImagemD", models.CharField(max_length=1)),
                ("revisaoCirurgiaoECDP", models.CharField(max_length=1)),
                ("qualRCECDP", models.CharField(max_length=15)),
                ("revisaoAnestesistaAPERU", models.CharField(max_length=1)),
                ("revisaoEnfermagemICEC", models.CharField(max_length=1)),
                ("palcaBisturiP", models.CharField(max_length=1)),
                ("equipamentoTestadoF", models.CharField(max_length=1)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="checklist.paciente",
                    ),
                ),
            ],
        ),
    ]
